name: App integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Unittesting routes
        env:
          FLASK_SECRET_KEY: lol
          DATABASE_URL2: sqlite:///db.sqlite
        run: |
          python3 -m pytest -v